# Generated by Django 5.2.4 on 2025-08-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus_connect", "0002_chatroom_message_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="campus_conn_sender__7ba41f_idx",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="group_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_size",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="reactions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campus_connect.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("read", "Read"),
                ],
                default="sent",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="thumbnails/"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("file", "File"),
                    ("voice", "Voice"),
                    ("video", "Video"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "status"], name="campus_conn_sender__11c80b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_read", "chat_room"], name="campus_conn_is_read_aef591_idx"
            ),
        ),
    ]
