# Generated by Django 5.2.4 on 2025-08-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campus_connect",
            "0003_remove_message_campus_conn_sender__7ba41f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
