# Generated by Django 5.2.4 on 2025-08-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus_connect", "0004_alter_message_duration_alter_message_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
