# Generated by Django 5.2.4 on 2025-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus_connect", "0005_alter_message_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[("Academics", "Academics"), ("General", "General")],
                max_length=50,
            ),
        ),
    ]
